project:
  type: website
  output-dir: docs

website:
  title: "Siyu Chen (陈思羽)"
  repo-url: https://github.com/SiyuChen1111/SiyuChen1111.github.io
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Contact"
        file: contact.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: article
